### ISSUE TITLE
Does this package really depend on attr, and not just attrs?

### ISSUE THREAD

**Issue by grandchild** [lwesterhof/semaphore#16]
I would like to package this library for Archlinux, and I was looking through the declared dependencies.

It seems like you don't really require this package: [`attr`](https://pypi.org/project/attr/), but only the module of the same name from this pacakge: [`attrs`](https://pypi.org/project/attrs/). But maybe I am mistaken?

`attr` is still a dependency in your `setup.py`.

**Comment by lwesterhof** [comment]
Thanks! Fixed in e276409da80bb2181d22339941c9235f076b60d2.
