### ISSUE TITLE
Keep a conversation going on

### ISSUE THREAD

**Issue by S7R1D3R** [lwesterhof/semaphore#18]
Hello all!

I am loving to make a simple bot using this library, but would like to know if there is any way for me to follow up a conversation. Like I already learn how to register the handlers and work with the received messages myself, as well as answer them. But is there any possibility of I knowing a certain person sent already sent some messages? Or is that for me to build?

Also would like to know if there is anyway for me to send a message to many contacts, like sending the same message to an array of numbers.

Enjoying a lot the library! Hope I can contribute one day! Even if it's documentation.

**Comment by lwesterhof** [comment]
Hi,

You can use the ChatContext [data](https://github.com/lwesterhof/semaphore/blob/08227ba025fa61b43d6897728b1f93f35d53dcde/semaphore/chat_context.py#L40) to store history of the messages sent by a certain persion. See the [timerbot](https://github.com/lwesterhof/semaphore/blob/08227ba025fa61b43d6897728b1f93f35d53dcde/examples/timerbot.py#L47) for example usage of the ChatContext data,  where use it to store all the jobs.

To send a message to multiple contact you can change the [source](https://github.com/lwesterhof/semaphore/blob/08227ba025fa61b43d6897728b1f93f35d53dcde/semaphore/message.py#L35) of the message you are replying to.
