### ISSUE TITLE
How to send images, voice, doc, video and sticker´s

### ISSUE THREAD

**Issue by jersonjunior** [lwesterhof/semaphore#19]
There is a possibility to send images, voice, doc, video and sticker´s?

**Comment by lwesterhof** [comment]
Yes, you can add attachments to the bot messages, see the XKCD bot for example (it adds an image in this case): https://github.com/lwesterhof/semaphore/blob/f1bd59a4bd06a853ca0188ef4a6f8b3e6fab1670/examples/xkcdbot.py#L53

**Comment by b3nks** [comment]
I am not able to send picture by looking at the examples. Should this do or am i missing something:
```
       attachment = {"filename": str("/path/to/file.jpg"),
                      "width": "100",
                      "height": "100"}
        await ctx.message.reply(body="picture", attachments=[attachment])
```

**Comment by lwesterhof** [comment]
That should do. Another example: https://github.com/lwesterhof/semaphore/blob/8ba266ef122cf04f7b556ae1348ca06bca194db2/examples/apodbot.py#L49
