### ISSUE TITLE
Send message without context

### ISSUE THREAD

**Issue by eknoes** [lwesterhof/semaphore#21]
As far as I can see, one needs a message to reply to to let the bot send a message and there is not really an interface to just send a message to User X.

My Bot sends out messages and may be restarted in between, so that something like in the timer example may not work. I would suggest to provide a `send(receiver, body, attachments=[])` on the for `semaphore.Bot`. If this would be a valid enhancement in your eyes, I would work on a PR.

**Comment by lwesterhof** [comment]
Yes, happy to receive a pull request 👍 If it is possible, an example bot using this functionality would be great.
