### ISSUE TITLE
Add option to wait for signald.send() confirmation

### ISSUE THREAD

**Issue by eknoes** [lwesterhof/semaphore#28]
Currently, semaphore just sends a message to Signald's socket and as client there is no chance to see whether sending was successful. But Signald answers with a [SendResponse](https://docs.signald.org/structures/v1/SendResponse.html), which contains whether sending a message was successful or not.

Imho, we should add an option like `confirm=False` which should be False by default - because this is the current behavior - but if True it listens for a `SendResponse`  and returns whether sending was successful or not. What do you think?

**Comment by lwesterhof** [comment]
Sounds like a good idea.

**Comment by eknoes** [comment]
So I'll start to implement this. I think this would lead to have to socket connections to `signald`, one for sending commands and listen for a response, and one for listening for messages and being subscribed to. Otherwise, it might happen that we listen for a response but get a new message or so. Do you agree? Would you prefer another solution to this that should be based on a single socket?

**Comment by thefinn93** [comment]
@eknoes you could the optional "id" field to track which response is associated with which request. It's not very well documented, see [#84](https://gitlab.com/signald/signald/-/issues/84) for a short explainer on how it works.

**Comment by eknoes** [comment]
Ah nice, so we can make sure to wait for the confirmation of the correct message and listen on the same socket!

Although, I am not yet sure if it would not make sense to have two different sockets, because otherwise those confirmation message handling would have to happen on the level of `bot.py`, as we have a `MessageSender` and a `MessageReceiver`. Or am I wrong? I am not that confident yet with Pythons `async` stuff and Socket communication.
