### ISSUE TITLE
Phone numbers

### ISSUE THREAD

**Issue by S7R1D3R** [lwesterhof/semaphore#33]
Hey, is there any way of converting a phone number to uuid or the reverse? I tought I had access to the phone number that sent the message to me in semaphore in the previous versions?

**Comment by S7R1D3R** [comment]
I am pretty sure that before updating my Semaphore-Bot the => ChatContext => message => source would be a phone number and now just appears as UUID. How can I access the sender phone number now? Or this a new update so numbers aren't linked by their API?

**Comment by lwesterhof** [comment]
Signal uses the UUID now as primary identifier. There can be phone numbers, but not necessary. What is your use case for accessing the phone numbers?

**Comment by S7R1D3R** [comment]
I have a DB with many contacts and I want to broadcast messages to all of them in a subscription app, it used to work only with phone numbers in my old code and now I have to access to the phone number to automatically add the correct UUID to it in the database.

By the way thanks for the support and I loved the library, If I feel confident will surely try to contribute to it and by next month make a donation. Just wanted to have a tutorial on using the data (ChatContext.data) and the job queues. Thank you.

**Comment by S7R1D3R** [comment]
Is there anyway to get the phone number? Would I need to develop a new part of the library? If yes, could you explain to me how would I do it? Or if there is a way to convert the UUID to the phone number.

**Comment by lwesterhof** [comment]
The MessageReceiver should store the phone number if it is available and the MessageSender should support both UUID and phone numbers. Then you can get the phone number of each contact. I will work on this when I find some time.
