### ISSUE TITLE
Update bot on docker

### ISSUE THREAD

**Issue by Baptaker** [lwesterhof/semaphore#59]
I am running the docker on my machine, it works fine with the  Bot example. I am trying to modify the bot , but everytime  I restart the docker my changes are not considered and the original bot is running. I guess I am missing a step, can the README of the docker be more specific on how to modify the docker's Bot ?

**Comment by lwesterhof** [comment]
I have added some instructions to the [README](https://github.com/lwesterhof/semaphore/blob/main/docker/README.md#update-the-bot), hope this solves your issue!

**Comment by Baptaker** [comment]
> I have added some instructions to the [README](https://github.com/lwesterhof/semaphore/blob/main/docker/README.md#update-the-bot), hope this solves your issue!

 Perfect! thank you!
