### ISSUE TITLE
signald unmaintained?

### ISSUE THREAD

**Issue by etvt** [lwesterhof/semaphore#66]
Is `signald` unmaintained at the moment? The account registration has not been working for 3 months, see https://gitlab.com/signald/signald/-/issues/375. Also, there has been no release for 9 months.

(Unfortunately, because of this, I am unable to use your amazing library, and might have to look for alternatives.)

**Comment by lwesterhof** [comment]
Yes, the account registration has not been working for some time now. However, I don't know if signald is unmaintained at the moment.

**Comment by etvt** [comment]
Ended up setting up the main account with signal-cli and linking signald to it. Not very convenient but it works for now.
