### ISSUE TITLE
I messed up the license metadata

### ISSUE THREAD

**Issue by iomintz** [lwesterhof/semaphore#8]
In #2 I changed the setup.py metadata to declare the license as AGPLv3, and I'm honestly not even sure why :sweat_smile:
Some of the code declared the license as GPLv3, and some declared it as LGPLv3, but nowhere is it AGPLv3. So I'm wondering, what license did you originally intend to use? Personally I think the AGPLv3 makes more sense for server-side code as it ensures all bots made using this library are open source as well, but it's up to you.

**Comment by lwesterhof** [comment]
Originally intended to use GPLv3 but the AGPLv3 makes more sense. I will fix this.

**Comment by iomintz** [comment]
OK. The headers and license file need to be updated.
